-- =============================================
-- MENTAL TENNIS DATABASE SCHEMA (PostgreSQL)
-- Author: MentalVIP Architecture Team
-- Date: 2026-01-16
-- =============================================

-- 1. ENUMS (Tipi di dato personalizzati)
-- Definisce i ruoli utente e gli stati delle scommesse
CREATE TYPE user_role AS ENUM ('admin', 'vip', 'free');
CREATE TYPE signal_status AS ENUM ('pending', 'won', 'lost', 'void');
CREATE TYPE sport_type AS ENUM ('tennis', 'soccer');

-- 2. PROFILES (Estensione di auth.users)
-- Questa tabella si collega alla gestione utenti nativa di Supabase/Firebase
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    role user_role DEFAULT 'free',
    subscription_start_date TIMESTAMP WITH TIME ZONE,
    subscription_end_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE profiles IS 'Dati estesi degli utenti registrati e stato abbonamento.';

-- 3. CATEGORIES (Lookup Table)
-- Gestisce gli sport e i colori associati per il frontend
CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    name sport_type NOT NULL UNIQUE,
    color_hex TEXT NOT NULL, -- Es: '#39FF14' per Tennis
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE categories IS 'Categorie sport e configurazione colori UI.';

-- 4. SIGNALS (Core Business Logic)
-- Tabella principale che contiene le giocate inserite dall'Admin
CREATE TABLE IF NOT EXISTS signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INT REFERENCES categories(id),
    title_match TEXT NOT NULL, -- Es: 'Sinner vs Alcaraz'
    competition TEXT,          -- Es: 'ATP Miami'
    prediction TEXT NOT NULL,  -- Es: 'Over 38.5'
    odds DECIMAL(5, 2) NOT NULL CHECK (odds > 1.00), -- La quota
    confidence TEXT DEFAULT 'High', -- Livello confidenza
    bookmaker_link TEXT,       -- Link affiliato
    status signal_status DEFAULT 'pending',
    is_vip_only BOOLEAN DEFAULT FALSE, -- Se TRUE, mostra il lucchetto ai FREE
    published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    result_score TEXT, -- Punteggio finale (opzionale)
    profit_loss DECIMAL(10, 2) -- Profitto/Perdita calcolato
);

COMMENT ON TABLE signals IS 'Storico e feed live delle giocate.';

-- 5. PERFORMANCE LOG (Analytics)
-- Tabella aggregata per i grafici di rendimento
CREATE TABLE IF NOT EXISTS performance_log (
    id SERIAL PRIMARY KEY,
    log_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_profit DECIMAL(10, 2) NOT NULL,
    win_rate DECIMAL(5, 2),
    total_bets INT
);

-- =============================================
-- SEED DATA (Dati Iniziali)
-- =============================================

-- Inserimento Categorie
INSERT INTO categories (name, color_hex) VALUES 
('tennis', '#39FF14'),
('soccer', '#00FFFF')
ON CONFLICT (name) DO NOTHING;

-- Esempio di Segnale (Opzionale)
INSERT INTO signals (category_id, title_match, competition, prediction, odds, status, is_vip_only)
VALUES 
(1, 'Sinner vs Djokovic', 'ATP Finals', 'Sinner Win', 1.85, 'pending', true);
